### ISSUE TITLE
Misspelled Secondary

### ISSUE THREAD

**Issue by Rfauss** [o0Adrian/flet-mvc#2]
In the routes examples, secondary is misspelled as "secundary" in every place it is used. I can fix it for you if you want.

**Comment by o0Adrian** [comment]
Fixed it, thanks!

**Comment by o0Adrian** [comment]
Though it won't be updated in PyPi until I add my menu control and the automatic page.update()
<img width="110" alt="image" src="https://github.com/o0Adrian/flet-mvc/assets/55646080/9a44c57e-3c10-4dfc-9ce4-a33e522ffd27">

**Comment by Rfauss** [comment]
I'll have to check it out. Thank you. I prefer to build from source usually
anyway.
